PUT http://localhost:3000/api/collectedOrder/64a2ac7b802ade2b3b62571c
Content-Type: text/xml

<order>
    <order_id>4</order_id>
    <order_status>Collected</order_status>
    <customer>Taina</customer>
    <address>Tainankatu 1</address>
    <postal_code>1234</postal_code>
    <city>Taina Polis</city>
    <phone>123456789</phone>
    <email>taina@taina.com</email>
    <items>
      <item>
        <name>Johto</name>
        <pcs>3</pcs>
        <product_id>10</product_id>
        <item_status>Collected</item_status>     
      </item>
      <item>
        <name>Nappi</name>
        <pcs>74</pcs>
        <product_id>1</product_id>
        <item_status>Collected</item_status>
      </item>
      <item>
        <name>Lanka</name>
        <pcs>15</pcs>
        <product_id>2</product_id>
        <item_status>Collected</item_status>
      </item>
      <item>
        <name>Ohje</name>
        <pcs>2</pcs>
        <product_id>3</product_id>
        <item_status>Collected</item_status>
      </item>
      <item>
        <name>Kevari</name>
        <pcs>1</pcs>
        <product_id>6</product_id>
        <item_status>Collected</item_status>
      </item>
    </items> 
  </order>